export  const ActionTypes={
    SETLIST:"SET_LIST_ITEMS",
    REMOVE_LIST:"REMOVE_LIST_ITEMS",
    SELECT_ITEM:"SET_SELECTED_ITEM",
    REMOVE_ITEM:"REMOVE_SELECTED_ITEM",
    ADD_CART:"ADD_CART_ITEM",
    REMOVE_ITEM_CART:"REMOVE_CART_ITEM"
}